// Cascade LFSR group module 
// bottom level LFSR seeds are stored external. Top level LFSR seeds are generated by bottom level.

module cascLFSR_16Tap(TRIG,RESET,OUT0,OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10,OUT11,OUT12,OUT13,OUT14,OUT15,SEED,SDcount);

input TRIG,RESET;
input [15:0] SEED; // bottom level LFSR seed
input [31:0] SDcount;

output [7:0] OUT0,OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9,OUT10,OUT11,OUT12,OUT13,OUT14,OUT15;

wire [15:0] SD_TOP; // top level LFSR seed

reg SDcountTOP_Flag = 1'b0;
reg SDcountBOT_Flag = 1'b0;
reg TOP_Flag, BOT_Flag  = 1'b1;

always @(posedge TRIG) begin
	if (TOP_Flag&SDcount[15]) begin
		TOP_Flag = 1'b0;
		SDcountTOP_Flag = 1'b1;
	end
	else if (SDcount[15]) begin
		SDcountTOP_Flag = 1'b0;
	end
	else TOP_Flag = 1'b1;
	
	if (BOT_Flag&SDcount[31]) begin
		BOT_Flag = 1'b0;
		SDcountBOT_Flag = 1'b1;
	end
	else if (SDcount[31]) begin
		SDcountBOT_Flag = 1'b0;
	end
	else BOT_Flag = 1'b1;
end

LFSR16_FullTap LFSRtop(
	.TRIG(TRIG),.RESET(SDcountTOP_Flag||RESET),
	.OUT0(OUT0),.OUT1(OUT1),.OUT2(OUT2),.OUT3(OUT3),.OUT4(OUT4),.OUT5(OUT5),.OUT6(OUT6),.OUT7(OUT7),.OUT8(OUT8),
	.OUT9(OUT9),.OUT10(OUT10),.OUT11(OUT11),.OUT12(OUT12),.OUT13(OUT13),.OUT14(OUT14),.OUT15(OUT15),
	.SEED(SD_TOP)
);

LFSR16 LFSRsub(.TRIG(SDcount[15]),.RESET(SDcountBOT_Flag||RESET),.OUT1(SD_TOP[7:0]),.OUT2(SD_TOP[15:8]),.SEED(SEED));


endmodule